### ISSUE TITLE
Incomplete Data

### ISSUE THREAD

**Issue by Akulen** [REINS-SJTU/EGAT-pytorch#2]
After downloading the linked drive data to `data/AMLSim/10K-merge-hard-batch`, there still happens to be some missing data, as I'm getting the error:
```
Traceback (most recent call last):
  File "/home/akulen/EGAT-pytorch/main.py", line 25, in <module>
    model = Trainer(wandb_logger.config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akulen/EGAT-pytorch/trainer/amlsim.py", line 26, in __init__
    dataset = self.dataset()
              ^^^^^^^^^^^^^^
  File "/home/akulen/EGAT-pytorch/trainer/amlsim.py", line 254, in dataset
    return BatchAMLSimDataset(root="data/AMLSim/10K-merge-hard-batch", transform=Compose([
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akulen/EGAT-pytorch/dataset.py", line 145, in __init__
    super().__init__(root, mode=mode, transform=transform, pre_transform=pre_transform)
  File "/home/akulen/EGAT-pytorch/dataset.py", line 16, in __init__
    super().__init__(root, transform=transform, pre_transform=pre_transform)
  File "/home/akulen/EGAT-pytorch/venv/lib/python3.11/site-packages/torch_geometric/data/in_memory_dataset.py", line 81, in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log,
  File "/home/akulen/EGAT-pytorch/venv/lib/python3.11/site-packages/torch_geometric/data/dataset.py", line 112, in __init__
    self._download()
  File "/home/akulen/EGAT-pytorch/venv/lib/python3.11/site-packages/torch_geometric/data/dataset.py", line 229, in _download
    self.download()
  File "/home/akulen/EGAT-pytorch/dataset.py", line 96, in download
    raise Exception("File not found: {}".format(f))
Exception: File not found: data/AMLSim/10K-merge-hard-batch/raw/labels.npy
```
I have the raw folder, containing 70 subfolders numbered between 0 and 84, some of which do contain a `labels.npy` file

**Comment by Bran-z1** [comment]
I encountered the same issue. I think it might be caused by the version of torch_geometric. Have you solved this problem?
